package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccidentHandle generated by hbm2java
 */
@Entity
@Table(name = "ACCIDENT_HANDLE")
public class AccidentHandle implements java.io.Serializable {

	private long id;
	private Date handleDate;
	private String outQuantity;
	private String process;
	private String result;
	private String surveyReport;

	public AccidentHandle() {
	}

	public AccidentHandle(long id) {
		this.id = id;
	}

	public AccidentHandle(long id, Date handleDate, String outQuantity,
			String process, String result, String surveyReport) {
		this.id = id;
		this.handleDate = handleDate;
		this.outQuantity = outQuantity;
		this.process = process;
		this.result = result;
		this.surveyReport = surveyReport;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HANDLE_DATE", length = 11)
	public Date getHandleDate() {
		return this.handleDate;
	}

	public void setHandleDate(Date handleDate) {
		this.handleDate = handleDate;
	}

	@Column(name = "OUT_QUANTITY", length = 510)
	public String getOutQuantity() {
		return this.outQuantity;
	}

	public void setOutQuantity(String outQuantity) {
		this.outQuantity = outQuantity;
	}

	@Column(name = "PROCESS", length = 510)
	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	@Column(name = "RESULT", length = 510)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "SURVEY_REPORT", length = 510)
	public String getSurveyReport() {
		return this.surveyReport;
	}

	public void setSurveyReport(String surveyReport) {
		this.surveyReport = surveyReport;
	}

}
