package com.systop.fsmis.model;

// Generated 2009-12-16 9:41:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AfterHandle generated by hbm2java
 */
@Entity
@Table(name = "AFTER_HANDLE")
public class AfterHandle implements java.io.Serializable {

	private long id;
	private String appeaseProgress;
	private Date handleDate;
	private String process;
	private String relatePersonnel;
	private String result;

	public AfterHandle() {
	}

	public AfterHandle(long id) {
		this.id = id;
	}

	public AfterHandle(long id, String appeaseProgress, Date handleDate,
			String process, String relatePersonnel, String result) {
		this.id = id;
		this.appeaseProgress = appeaseProgress;
		this.handleDate = handleDate;
		this.process = process;
		this.relatePersonnel = relatePersonnel;
		this.result = result;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "APPEASE_PROGRESS", length = 510)
	public String getAppeaseProgress() {
		return this.appeaseProgress;
	}

	public void setAppeaseProgress(String appeaseProgress) {
		this.appeaseProgress = appeaseProgress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HANDLE_DATE", length = 11)
	public Date getHandleDate() {
		return this.handleDate;
	}

	public void setHandleDate(Date handleDate) {
		this.handleDate = handleDate;
	}

	@Column(name = "PROCESS", length = 510)
	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	@Column(name = "RELATE_PERSONNEL", length = 510)
	public String getRelatePersonnel() {
		return this.relatePersonnel;
	}

	public void setRelatePersonnel(String relatePersonnel) {
		this.relatePersonnel = relatePersonnel;
	}

	@Column(name = "RESULT", length = 510)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
