package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Assessment generated by hbm2java
 */
@Entity
@Table(name = "ASSESSMENT")
public class Assessment implements java.io.Serializable {

	private long id;
	private GenericCase genericCase;
	private CompositiveCase compositiveCase;
	private Date askDate;
	private Clob askCause;
	private Date auditDate;
	private Character isConsent;
	private Date resultDate;
	private String result;
	private Character isComplete;
	private Long leaderId;
	private Set<Expert> experts = new HashSet<Expert>(0);
	private Set<AssessmentAttach> assessmentAttachs = new HashSet<AssessmentAttach>(
			0);

	public Assessment() {
	}

	public Assessment(long id) {
		this.id = id;
	}

	public Assessment(long id, GenericCase genericCase,
			CompositiveCase compositiveCase, Date askDate, Clob askCause,
			Date auditDate, Character isConsent, Date resultDate,
			String result, Character isComplete, Long leaderId,
			Set<Expert> experts, Set<AssessmentAttach> assessmentAttachs) {
		this.id = id;
		this.genericCase = genericCase;
		this.compositiveCase = compositiveCase;
		this.askDate = askDate;
		this.askCause = askCause;
		this.auditDate = auditDate;
		this.isConsent = isConsent;
		this.resultDate = resultDate;
		this.result = result;
		this.isComplete = isComplete;
		this.leaderId = leaderId;
		this.experts = experts;
		this.assessmentAttachs = assessmentAttachs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GENERIC_CASE")
	public GenericCase getGenericCase() {
		return this.genericCase;
	}

	public void setGenericCase(GenericCase genericCase) {
		this.genericCase = genericCase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPOSITIVE_CASE")
	public CompositiveCase getCompositiveCase() {
		return this.compositiveCase;
	}

	public void setCompositiveCase(CompositiveCase compositiveCase) {
		this.compositiveCase = compositiveCase;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ASK_DATE", length = 11)
	public Date getAskDate() {
		return this.askDate;
	}

	public void setAskDate(Date askDate) {
		this.askDate = askDate;
	}

	@Column(name = "ASK_CAUSE")
	public Clob getAskCause() {
		return this.askCause;
	}

	public void setAskCause(Clob askCause) {
		this.askCause = askCause;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUDIT_DATE", length = 11)
	public Date getAuditDate() {
		return this.auditDate;
	}

	public void setAuditDate(Date auditDate) {
		this.auditDate = auditDate;
	}

	@Column(name = "IS_CONSENT", length = 1)
	public Character getIsConsent() {
		return this.isConsent;
	}

	public void setIsConsent(Character isConsent) {
		this.isConsent = isConsent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RESULT_DATE", length = 11)
	public Date getResultDate() {
		return this.resultDate;
	}

	public void setResultDate(Date resultDate) {
		this.resultDate = resultDate;
	}

	@Column(name = "RESULT", length = 4000)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "IS_COMPLETE", length = 1)
	public Character getIsComplete() {
		return this.isComplete;
	}

	public void setIsComplete(Character isComplete) {
		this.isComplete = isComplete;
	}

	@Column(name = "LEADER_ID", precision = 10, scale = 0)
	public Long getLeaderId() {
		return this.leaderId;
	}

	public void setLeaderId(Long leaderId) {
		this.leaderId = leaderId;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ASSESSMENT_EXPERT", joinColumns = { @JoinColumn(name = "ASSESSMENT_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "EXPERT_ID", nullable = false, updatable = false) })
	public Set<Expert> getExperts() {
		return this.experts;
	}

	public void setExperts(Set<Expert> experts) {
		this.experts = experts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assessment")
	public Set<AssessmentAttach> getAssessmentAttachs() {
		return this.assessmentAttachs;
	}

	public void setAssessmentAttachs(Set<AssessmentAttach> assessmentAttachs) {
		this.assessmentAttachs = assessmentAttachs;
	}

}
