package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Defend generated by hbm2java
 */
@Entity
@Table(name = "DEFEND")
public class Defend implements java.io.Serializable {

	private long id;
	private String dispersedQuantity;
	private Date handleDate;
	private String policeQuantity;
	private String process;
	private String result;

	public Defend() {
	}

	public Defend(long id) {
		this.id = id;
	}

	public Defend(long id, String dispersedQuantity, Date handleDate,
			String policeQuantity, String process, String result) {
		this.id = id;
		this.dispersedQuantity = dispersedQuantity;
		this.handleDate = handleDate;
		this.policeQuantity = policeQuantity;
		this.process = process;
		this.result = result;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "DISPERSED_QUANTITY", length = 510)
	public String getDispersedQuantity() {
		return this.dispersedQuantity;
	}

	public void setDispersedQuantity(String dispersedQuantity) {
		this.dispersedQuantity = dispersedQuantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HANDLE_DATE", length = 11)
	public Date getHandleDate() {
		return this.handleDate;
	}

	public void setHandleDate(Date handleDate) {
		this.handleDate = handleDate;
	}

	@Column(name = "POLICE_QUANTITY", length = 510)
	public String getPoliceQuantity() {
		return this.policeQuantity;
	}

	public void setPoliceQuantity(String policeQuantity) {
		this.policeQuantity = policeQuantity;
	}

	@Column(name = "PROCESS", length = 510)
	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	@Column(name = "RESULT", length = 510)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
