package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExpertTechnology generated by hbm2java
 */
@Entity
@Table(name = "EXPERT_TECHNOLOGY")
public class ExpertTechnology implements java.io.Serializable {

	private long id;
	private String analyseReport;
	private String expertGroup;
	private Date handleDate;
	private String process;
	private String result;

	public ExpertTechnology() {
	}

	public ExpertTechnology(long id) {
		this.id = id;
	}

	public ExpertTechnology(long id, String analyseReport, String expertGroup,
			Date handleDate, String process, String result) {
		this.id = id;
		this.analyseReport = analyseReport;
		this.expertGroup = expertGroup;
		this.handleDate = handleDate;
		this.process = process;
		this.result = result;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ANALYSE_REPORT", length = 510)
	public String getAnalyseReport() {
		return this.analyseReport;
	}

	public void setAnalyseReport(String analyseReport) {
		this.analyseReport = analyseReport;
	}

	@Column(name = "EXPERT_GROUP", length = 510)
	public String getExpertGroup() {
		return this.expertGroup;
	}

	public void setExpertGroup(String expertGroup) {
		this.expertGroup = expertGroup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HANDLE_DATE", length = 11)
	public Date getHandleDate() {
		return this.handleDate;
	}

	public void setHandleDate(Date handleDate) {
		this.handleDate = handleDate;
	}

	@Column(name = "PROCESS", length = 510)
	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	@Column(name = "RESULT", length = 510)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
