package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExpertCategory generated by hbm2java
 */
@Entity
@Table(name = "EXPERT_CATEGORY")
public class ExpertCategory implements java.io.Serializable {

	private long id;
	private String name;
	private String descb;
	private Set<Expert> experts = new HashSet<Expert>(0);

	public ExpertCategory() {
	}

	public ExpertCategory(long id) {
		this.id = id;
	}

	public ExpertCategory(long id, String name, String descb,
			Set<Expert> experts) {
		this.id = id;
		this.name = name;
		this.descb = descb;
		this.experts = experts;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCB", length = 500)
	public String getDescb() {
		return this.descb;
	}

	public void setDescb(String descb) {
		this.descb = descb;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expertCategory")
	public Set<Expert> getExperts() {
		return this.experts;
	}

	public void setExperts(Set<Expert> experts) {
		this.experts = experts;
	}

}
