package com.systop.fsmis.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExpertGroups generated by hbm2java
 */
@Entity
@Table(name = "EXPERT_GROUPS")
public class ExpertGroup implements java.io.Serializable {

	private long id;
	private Expert leader;
	private Assessment assessment;
	private String members;

	public ExpertGroup() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEADER")
	public Expert getLeader() {
		return this.leader;
	}

	public void setLeader(Expert leader) {
		this.leader = leader;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASSESSMENT")
	public Assessment getAssessment() {
		return this.assessment;
	}

	public void setAssessment(Assessment assessment) {
		this.assessment = assessment;
	}

	@Column(name = "MEMBERS", length = 500)
	public String getMembers() {
		return this.members;
	}

	public void setMembers(String members) {
		this.members = members;
	}

}
