package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JointTask generated by hbm2java
 */
@Entity
@Table(name = "JOINT_TASK")
public class JointTask implements java.io.Serializable {

	private long id;
	private GenericCase genericCase;
	private CompositiveCase compositiveCase;
	private String title;
	private String descn;
	private String proposer;
	private Date createDate;
	private Date presetTime;
	private String remark;
	private Character status;
	private Long auditor;
	private Character isAgree;
	private String opinion;
	private Date auditDate;
	private Set<JointTaskDetail> jointTaskDetails = new HashSet<JointTaskDetail>(
			0);
	private Set<JointTaskAttach> jointTaskAttachs = new HashSet<JointTaskAttach>(
			0);

	public JointTask() {
	}

	public JointTask(long id) {
		this.id = id;
	}

	public JointTask(long id, GenericCase genericCase,
			CompositiveCase compositiveCase, String title, String descn,
			String proposer, Date createDate, Date presetTime, String remark,
			Character status, Long auditor, Character isAgree, String opinion,
			Date auditDate, Set<JointTaskDetail> jointTaskDetails,
			Set<JointTaskAttach> jointTaskAttachs) {
		this.id = id;
		this.genericCase = genericCase;
		this.compositiveCase = compositiveCase;
		this.title = title;
		this.descn = descn;
		this.proposer = proposer;
		this.createDate = createDate;
		this.presetTime = presetTime;
		this.remark = remark;
		this.status = status;
		this.auditor = auditor;
		this.isAgree = isAgree;
		this.opinion = opinion;
		this.auditDate = auditDate;
		this.jointTaskDetails = jointTaskDetails;
		this.jointTaskAttachs = jointTaskAttachs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GENERIC_CASE")
	public GenericCase getGenericCase() {
		return this.genericCase;
	}

	public void setGenericCase(GenericCase genericCase) {
		this.genericCase = genericCase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPOSITIVE_CASE")
	public CompositiveCase getCompositiveCase() {
		return this.compositiveCase;
	}

	public void setCompositiveCase(CompositiveCase compositiveCase) {
		this.compositiveCase = compositiveCase;
	}

	@Column(name = "TITLE", length = 510)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCN", length = 4000)
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	@Column(name = "PROPOSER", length = 110)
	public String getProposer() {
		return this.proposer;
	}

	public void setProposer(String proposer) {
		this.proposer = proposer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 11)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRESET_TIME", length = 11)
	public Date getPresetTime() {
		return this.presetTime;
	}

	public void setPresetTime(Date presetTime) {
		this.presetTime = presetTime;
	}

	@Column(name = "REMARK", length = 510)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "AUDITOR", precision = 10, scale = 0)
	public Long getAuditor() {
		return this.auditor;
	}

	public void setAuditor(Long auditor) {
		this.auditor = auditor;
	}

	@Column(name = "IS_AGREE", length = 1)
	public Character getIsAgree() {
		return this.isAgree;
	}

	public void setIsAgree(Character isAgree) {
		this.isAgree = isAgree;
	}

	@Column(name = "OPINION", length = 510)
	public String getOpinion() {
		return this.opinion;
	}

	public void setOpinion(String opinion) {
		this.opinion = opinion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUDIT_DATE", length = 11)
	public Date getAuditDate() {
		return this.auditDate;
	}

	public void setAuditDate(Date auditDate) {
		this.auditDate = auditDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jointTask")
	public Set<JointTaskDetail> getJointTaskDetails() {
		return this.jointTaskDetails;
	}

	public void setJointTaskDetails(Set<JointTaskDetail> jointTaskDetails) {
		this.jointTaskDetails = jointTaskDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jointTask")
	public Set<JointTaskAttach> getJointTaskAttachs() {
		return this.jointTaskAttachs;
	}

	public void setJointTaskAttachs(Set<JointTaskAttach> jointTaskAttachs) {
		this.jointTaskAttachs = jointTaskAttachs;
	}

}
