package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "MESSAGE")
public class Message implements java.io.Serializable {

	private long id;
	private String content;
	private Date createTime;
	private Date receiveTime;
	private Character isNew;

	public Message() {
	}

	public Message(long id) {
		this.id = id;
	}

	public Message(long id, String content, Date createTime, Date receiveTime,
			Character isNew) {
		this.id = id;
		this.content = content;
		this.createTime = createTime;
		this.receiveTime = receiveTime;
		this.isNew = isNew;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CONTENT", length = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 11)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECEIVE_TIME", length = 11)
	public Date getReceiveTime() {
		return this.receiveTime;
	}

	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	@Column(name = "IS_NEW", length = 1)
	public Character getIsNew() {
		return this.isNew;
	}

	public void setIsNew(Character isNew) {
		this.isNew = isNew;
	}

}
