package com.systop.fsmis.model;

// Generated 2009-12-16 9:41:03 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Permissions generated by hbm2java
 */
@Entity
@Table(name = "PERMISSIONS")
public class Permissions implements java.io.Serializable {

	private long id;
	private Long version;
	private String descn;
	private Character isSys;
	private String name;
	private String operation;
	private String status;
	private Set<Roles> roleses = new HashSet<Roles>(0);
	private Set<Resources> resourceses = new HashSet<Resources>(0);

	public Permissions() {
	}

	public Permissions(long id) {
		this.id = id;
	}

	public Permissions(long id, String descn, Character isSys, String name,
			String operation, String status, Set<Roles> roleses,
			Set<Resources> resourceses) {
		this.id = id;
		this.descn = descn;
		this.isSys = isSys;
		this.name = name;
		this.operation = operation;
		this.status = status;
		this.roleses = roleses;
		this.resourceses = resourceses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", precision = 10, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "DESCN", length = 510)
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	@Column(name = "IS_SYS", length = 1)
	public Character getIsSys() {
		return this.isSys;
	}

	public void setIsSys(Character isSys) {
		this.isSys = isSys;
	}

	@Column(name = "NAME", length = 510)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "OPERATION", length = 510)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "STATUS", length = 510)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ROLE_PERMIS", joinColumns = { @JoinColumn(name = "PERMISSION_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) })
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "PERMIS_RESC", joinColumns = { @JoinColumn(name = "PERMISSION_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "RESC_ID", nullable = false, updatable = false) })
	public Set<Resources> getResourceses() {
		return this.resourceses;
	}

	public void setResourceses(Set<Resources> resourceses) {
		this.resourceses = resourceses;
	}

}
