package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Receive generated by hbm2java
 */
@Entity
@Table(name = "RECEIVE")
public class Receive implements java.io.Serializable {

	private long id;
	private String connectionDetails;
	private Date handleDate;
	private String process;
	private String receiveThing;
	private String result;

	public Receive() {
	}

	public Receive(long id) {
		this.id = id;
	}

	public Receive(long id, String connectionDetails, Date handleDate,
			String process, String receiveThing, String result) {
		this.id = id;
		this.connectionDetails = connectionDetails;
		this.handleDate = handleDate;
		this.process = process;
		this.receiveThing = receiveThing;
		this.result = result;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CONNECTION_DETAILS", length = 510)
	public String getConnectionDetails() {
		return this.connectionDetails;
	}

	public void setConnectionDetails(String connectionDetails) {
		this.connectionDetails = connectionDetails;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HANDLE_DATE", length = 11)
	public Date getHandleDate() {
		return this.handleDate;
	}

	public void setHandleDate(Date handleDate) {
		this.handleDate = handleDate;
	}

	@Column(name = "PROCESS", length = 510)
	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	@Column(name = "RECEIVE_THING", length = 510)
	public String getReceiveThing() {
		return this.receiveThing;
	}

	public void setReceiveThing(String receiveThing) {
		this.receiveThing = receiveThing;
	}

	@Column(name = "RESULT", length = 510)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
