package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmsCount generated by hbm2java
 */
@Entity
@Table(name = "SMS_COUNT")
public class SmsCount implements java.io.Serializable {

	private long id;
	private Long mobileCount;
	private Long otherCount;
	private Date sendDate;

	public SmsCount() {
	}

	public SmsCount(long id) {
		this.id = id;
	}

	public SmsCount(long id, Long mobileCount, Long otherCount, Date sendDate) {
		this.id = id;
		this.mobileCount = mobileCount;
		this.otherCount = otherCount;
		this.sendDate = sendDate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "MOBILE_COUNT", precision = 10, scale = 0)
	public Long getMobileCount() {
		return this.mobileCount;
	}

	public void setMobileCount(Long mobileCount) {
		this.mobileCount = mobileCount;
	}

	@Column(name = "OTHER_COUNT", precision = 10, scale = 0)
	public Long getOtherCount() {
		return this.otherCount;
	}

	public void setOtherCount(Long otherCount) {
		this.otherCount = otherCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SEND_DATE", length = 11)
	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

}
