package com.systop.fsmis.model;

// Generated 2009-12-16 9:41:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmsReceive generated by hbm2java
 */
@Entity
@Table(name = "SMS_RECEIVE")
public class SmsReceive implements java.io.Serializable {

	private long id;
	private GenericCase genericCase;
	private String content;
	private String mobileNum;
	private String isNew;
	private Date receiveTime;
	private Date sendTime;
	private String isParsed;
	private String isReport;
	private String isTreated;
	private String isVerify;
	private String remark;

	public SmsReceive() {
	}

	public SmsReceive(long id) {
		this.id = id;
	}

	public SmsReceive(long id, GenericCase genericCase, String content,
			String mobileNum, String isNew, Date receiveTime, Date sendTime,
			String isParsed, String isReport, String isTreated,
			String isVerify, String remark) {
		this.id = id;
		this.genericCase = genericCase;
		this.content = content;
		this.mobileNum = mobileNum;
		this.isNew = isNew;
		this.receiveTime = receiveTime;
		this.sendTime = sendTime;
		this.isParsed = isParsed;
		this.isReport = isReport;
		this.isTreated = isTreated;
		this.isVerify = isVerify;
		this.remark = remark;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GENERIC_CASE")
	public GenericCase getGenericCase() {
		return this.genericCase;
	}

	public void setGenericCase(GenericCase genericCase) {
		this.genericCase = genericCase;
	}

	@Column(name = "CONTENT", length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "MOBILE_NUM", length = 40)
	public String getMobileNum() {
		return this.mobileNum;
	}

	public void setMobileNum(String mobileNum) {
		this.mobileNum = mobileNum;
	}

	@Column(name = "IS_NEW", length = 2)
	public String getIsNew() {
		return this.isNew;
	}

	public void setIsNew(String isNew) {
		this.isNew = isNew;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECEIVE_TIME", length = 11)
	public Date getReceiveTime() {
		return this.receiveTime;
	}

	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SEND_TIME", length = 11)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "IS_PARSED", length = 2)
	public String getIsParsed() {
		return this.isParsed;
	}

	public void setIsParsed(String isParsed) {
		this.isParsed = isParsed;
	}

	@Column(name = "IS_REPORT", length = 2)
	public String getIsReport() {
		return this.isReport;
	}

	public void setIsReport(String isReport) {
		this.isReport = isReport;
	}

	@Column(name = "IS_TREATED", length = 510)
	public String getIsTreated() {
		return this.isTreated;
	}

	public void setIsTreated(String isTreated) {
		this.isTreated = isTreated;
	}

	@Column(name = "IS_VERIFY", length = 510)
	public String getIsVerify() {
		return this.isVerify;
	}

	public void setIsVerify(String isVerify) {
		this.isVerify = isVerify;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
