package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Supervisor generated by hbm2java
 */
@Entity
@Table(name = "SUPERVISOR")
public class Supervisor implements java.io.Serializable {

	private long id;
	private Depts depts;
	private String name;
	private String gender;
	private Date birthday;
	private String code;
	private String unit;
	private String duty;
	private String mobile;
	private String phone;
	private String superviseRegion;
	private String coordinate;
	private String photoUrl;
	private Character isLeader;
	private Set<GenericCase> genericCases = new HashSet<GenericCase>(0);

	public Supervisor() {
	}

	public Supervisor(long id) {
		this.id = id;
	}

	public Supervisor(long id, Depts depts, String name, String gender,
			Date birthday, String code, String unit, String duty,
			String mobile, String phone, String superviseRegion,
			String coordinate, String photoUrl, Character isLeader,
			Set<GenericCase> genericCases) {
		this.id = id;
		this.depts = depts;
		this.name = name;
		this.gender = gender;
		this.birthday = birthday;
		this.code = code;
		this.unit = unit;
		this.duty = duty;
		this.mobile = mobile;
		this.phone = phone;
		this.superviseRegion = superviseRegion;
		this.coordinate = coordinate;
		this.photoUrl = photoUrl;
		this.isLeader = isLeader;
		this.genericCases = genericCases;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPT")
	public Depts getDepts() {
		return this.depts;
	}

	public void setDepts(Depts depts) {
		this.depts = depts;
	}

	@Column(name = "NAME", length = 510)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "GENDER", length = 4)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BIRTHDAY", length = 11)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "CODE", length = 510)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "UNIT", length = 510)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "DUTY", length = 510)
	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	@Column(name = "MOBILE", length = 510)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "PHONE", length = 510)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "SUPERVISE_REGION", length = 510)
	public String getSuperviseRegion() {
		return this.superviseRegion;
	}

	public void setSuperviseRegion(String superviseRegion) {
		this.superviseRegion = superviseRegion;
	}

	@Column(name = "COORDINATE", length = 510)
	public String getCoordinate() {
		return this.coordinate;
	}

	public void setCoordinate(String coordinate) {
		this.coordinate = coordinate;
	}

	@Column(name = "PHOTO_URL", length = 510)
	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

	@Column(name = "IS_LEADER", length = 1)
	public Character getIsLeader() {
		return this.isLeader;
	}

	public void setIsLeader(Character isLeader) {
		this.isLeader = isLeader;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supervisor")
	public Set<GenericCase> getGenericCases() {
		return this.genericCases;
	}

	public void setGenericCases(Set<GenericCase> genericCases) {
		this.genericCases = genericCases;
	}

}
