package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS")
public class Users implements java.io.Serializable {

	private long id;
	private Long version;
	private String name;
	private String sez;
	private Date birthday;
	private String folk;
	private String HTel;
	private String mobile;
	private String email;
	private String descn;
	private Character isMesreceive;
	private Character isSys;
	private String lastLoginIp;
	private Date lastLoginTime;
	private String loginId;
	private Long loginTimes;
	private String password;
	private String photo;
	private String post;
	private String status;
	private String userType;
	private Long deptId;

	public Users() {
	}

	public Users(long id) {
		this.id = id;
	}

	public Users(long id, String name, String sez, Date birthday, String folk,
			String HTel, String mobile, String email, String descn,
			Character isMesreceive, Character isSys, String lastLoginIp,
			Date lastLoginTime, String loginId, Long loginTimes,
			String password, String photo, String post, String status,
			String userType, Long deptId) {
		this.id = id;
		this.name = name;
		this.sez = sez;
		this.birthday = birthday;
		this.folk = folk;
		this.HTel = HTel;
		this.mobile = mobile;
		this.email = email;
		this.descn = descn;
		this.isMesreceive = isMesreceive;
		this.isSys = isSys;
		this.lastLoginIp = lastLoginIp;
		this.lastLoginTime = lastLoginTime;
		this.loginId = loginId;
		this.loginTimes = loginTimes;
		this.password = password;
		this.photo = photo;
		this.post = post;
		this.status = status;
		this.userType = userType;
		this.deptId = deptId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", precision = 10, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "NAME", length = 510)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SEZ", length = 510)
	public String getSez() {
		return this.sez;
	}

	public void setSez(String sez) {
		this.sez = sez;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BIRTHDAY", length = 11)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "FOLK")
	public String getFolk() {
		return this.folk;
	}

	public void setFolk(String folk) {
		this.folk = folk;
	}

	@Column(name = "H_TEL", length = 510)
	public String getHTel() {
		return this.HTel;
	}

	public void setHTel(String HTel) {
		this.HTel = HTel;
	}

	@Column(name = "MOBILE", length = 510)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "EMAIL", length = 510)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "DESCN", length = 510)
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	@Column(name = "IS_MESRECEIVE", length = 1)
	public Character getIsMesreceive() {
		return this.isMesreceive;
	}

	public void setIsMesreceive(Character isMesreceive) {
		this.isMesreceive = isMesreceive;
	}

	@Column(name = "IS_SYS", length = 1)
	public Character getIsSys() {
		return this.isSys;
	}

	public void setIsSys(Character isSys) {
		this.isSys = isSys;
	}

	@Column(name = "LAST_LOGIN_IP", length = 510)
	public String getLastLoginIp() {
		return this.lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_LOGIN_TIME", length = 11)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	@Column(name = "LOGIN_ID", length = 510)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "LOGIN_TIMES", precision = 10, scale = 0)
	public Long getLoginTimes() {
		return this.loginTimes;
	}

	public void setLoginTimes(Long loginTimes) {
		this.loginTimes = loginTimes;
	}

	@Column(name = "PASSWORD", length = 510)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "PHOTO", length = 510)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "POST", length = 510)
	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	@Column(name = "STATUS", length = 510)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "USER_TYPE", length = 510)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "DEPT_ID", precision = 10, scale = 0)
	public Long getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

}
