package com.systop.fsmis.model;

// Generated 2009-12-16 9:41:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Enterprise generated by hbm2java
 */
@Entity
@Table(name = "ENTERPRISE")
public class Enterprise implements java.io.Serializable {

	private long id;
	private Depts depts;
	private String name;
	private String descn;
	private String code;
	private String idNumber;
	private String integrityGrade;
	private String integrityRecord;
	private String legalPerson;
	private String mobile;
	private String phone;
	private String address;
	private String coordinate;
	private String zip;
	private String operateDetails;
	private String photoUrl;
	private String remark;
	private String businessLicense;
	private Date businessLicenseIndate;
	private String produceLicense;
	private Date produceLicenseIndate;
	private String sanitationLicense;
	private Date sanitationLicenseIndate;
	private Set<GenericCase> genericCases = new HashSet<GenericCase>(0);

	public Enterprise() {
	}

	public Enterprise(long id) {
		this.id = id;
	}

	public Enterprise(long id, Depts depts, String name, String descn,
			String code, String idNumber, String integrityGrade,
			String integrityRecord, String legalPerson, String mobile,
			String phone, String address, String coordinate, String zip,
			String operateDetails, String photoUrl, String remark,
			String businessLicense, Date businessLicenseIndate,
			String produceLicense, Date produceLicenseIndate,
			String sanitationLicense, Date sanitationLicenseIndate,
			Set<GenericCase> genericCases) {
		this.id = id;
		this.depts = depts;
		this.name = name;
		this.descn = descn;
		this.code = code;
		this.idNumber = idNumber;
		this.integrityGrade = integrityGrade;
		this.integrityRecord = integrityRecord;
		this.legalPerson = legalPerson;
		this.mobile = mobile;
		this.phone = phone;
		this.address = address;
		this.coordinate = coordinate;
		this.zip = zip;
		this.operateDetails = operateDetails;
		this.photoUrl = photoUrl;
		this.remark = remark;
		this.businessLicense = businessLicense;
		this.businessLicenseIndate = businessLicenseIndate;
		this.produceLicense = produceLicense;
		this.produceLicenseIndate = produceLicenseIndate;
		this.sanitationLicense = sanitationLicense;
		this.sanitationLicenseIndate = sanitationLicenseIndate;
		this.genericCases = genericCases;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPT")
	public Depts getDepts() {
		return this.depts;
	}

	public void setDepts(Depts depts) {
		this.depts = depts;
	}

	@Column(name = "NAME", length = 510)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCN", length = 4000)
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	@Column(name = "CODE", length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "ID_NUMBER", length = 100)
	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	@Column(name = "INTEGRITY_GRADE", length = 100)
	public String getIntegrityGrade() {
		return this.integrityGrade;
	}

	public void setIntegrityGrade(String integrityGrade) {
		this.integrityGrade = integrityGrade;
	}

	@Column(name = "INTEGRITY_RECORD", length = 4000)
	public String getIntegrityRecord() {
		return this.integrityRecord;
	}

	public void setIntegrityRecord(String integrityRecord) {
		this.integrityRecord = integrityRecord;
	}

	@Column(name = "LEGAL_PERSON", length = 100)
	public String getLegalPerson() {
		return this.legalPerson;
	}

	public void setLegalPerson(String legalPerson) {
		this.legalPerson = legalPerson;
	}

	@Column(name = "MOBILE", length = 100)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "PHONE", length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "ADDRESS", length = 510)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "COORDINATE", length = 510)
	public String getCoordinate() {
		return this.coordinate;
	}

	public void setCoordinate(String coordinate) {
		this.coordinate = coordinate;
	}

	@Column(name = "ZIP", length = 40)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "OPERATE_DETAILS", length = 510)
	public String getOperateDetails() {
		return this.operateDetails;
	}

	public void setOperateDetails(String operateDetails) {
		this.operateDetails = operateDetails;
	}

	@Column(name = "PHOTO_URL", length = 510)
	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

	@Column(name = "REMARK", length = 510)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "BUSINESS_LICENSE", length = 510)
	public String getBusinessLicense() {
		return this.businessLicense;
	}

	public void setBusinessLicense(String businessLicense) {
		this.businessLicense = businessLicense;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BUSINESS_LICENSE_INDATE", length = 11)
	public Date getBusinessLicenseIndate() {
		return this.businessLicenseIndate;
	}

	public void setBusinessLicenseIndate(Date businessLicenseIndate) {
		this.businessLicenseIndate = businessLicenseIndate;
	}

	@Column(name = "PRODUCE_LICENSE", length = 510)
	public String getProduceLicense() {
		return this.produceLicense;
	}

	public void setProduceLicense(String produceLicense) {
		this.produceLicense = produceLicense;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRODUCE_LICENSE_INDATE", length = 11)
	public Date getProduceLicenseIndate() {
		return this.produceLicenseIndate;
	}

	public void setProduceLicenseIndate(Date produceLicenseIndate) {
		this.produceLicenseIndate = produceLicenseIndate;
	}

	@Column(name = "SANITATION_LICENSE", length = 510)
	public String getSanitationLicense() {
		return this.sanitationLicense;
	}

	public void setSanitationLicense(String sanitationLicense) {
		this.sanitationLicense = sanitationLicense;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SANITATION_LICENSE_INDATE", length = 11)
	public Date getSanitationLicenseIndate() {
		return this.sanitationLicenseIndate;
	}

	public void setSanitationLicenseIndate(Date sanitationLicenseIndate) {
		this.sanitationLicenseIndate = sanitationLicenseIndate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enterprise")
	public Set<GenericCase> getGenericCases() {
		return this.genericCases;
	}

	public void setGenericCases(Set<GenericCase> genericCases) {
		this.genericCases = genericCases;
	}

}
