package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expert generated by hbm2java
 */
@Entity
@Table(name = "EXPERT")
public class Expert implements java.io.Serializable {

	private long id;
	private ExpertCategory expertCategory;
	private String name;
	private Date birthDate;
	private String graduateSchool;
	private String schoolRecord;
	private String degree;
	private String mobile;
	private String homePhone;
	private String officePhone;
	private String email;
	private String photoPath;
	private String units;
	private String position;
	private String title;
	private String research;
	private Clob summery;
	private String remark;
	private String level;
	private Set<Assessment> assessments = new HashSet<Assessment>(0);

	public Expert() {
	}

	public Expert(long id) {
		this.id = id;
	}

	public Expert(long id, ExpertCategory expertCategory, String name,
			Date birthDate, String graduateSchool, String schoolRecord,
			String degree, String mobile, String homePhone, String officePhone,
			String email, String photoPath, String units, String position,
			String title, String research, Clob summery, String remark,
			String level, Set<Assessment> assessments) {
		this.id = id;
		this.expertCategory = expertCategory;
		this.name = name;
		this.birthDate = birthDate;
		this.graduateSchool = graduateSchool;
		this.schoolRecord = schoolRecord;
		this.degree = degree;
		this.mobile = mobile;
		this.homePhone = homePhone;
		this.officePhone = officePhone;
		this.email = email;
		this.photoPath = photoPath;
		this.units = units;
		this.position = position;
		this.title = title;
		this.research = research;
		this.summery = summery;
		this.remark = remark;
		this.level = level;
		this.assessments = assessments;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXPERT_CATEGORY")
	public ExpertCategory getExpertCategory() {
		return this.expertCategory;
	}

	public void setExpertCategory(ExpertCategory expertCategory) {
		this.expertCategory = expertCategory;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BIRTH_DATE", length = 11)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "GRADUATE_SCHOOL", length = 110)
	public String getGraduateSchool() {
		return this.graduateSchool;
	}

	public void setGraduateSchool(String graduateSchool) {
		this.graduateSchool = graduateSchool;
	}

	@Column(name = "SCHOOL_RECORD", length = 110)
	public String getSchoolRecord() {
		return this.schoolRecord;
	}

	public void setSchoolRecord(String schoolRecord) {
		this.schoolRecord = schoolRecord;
	}

	@Column(name = "DEGREE", length = 110)
	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	@Column(name = "MOBILE", length = 110)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "HOME_PHONE", length = 110)
	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	@Column(name = "OFFICE_PHONE", length = 110)
	public String getOfficePhone() {
		return this.officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	@Column(name = "EMAIL", length = 510)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHOTO_PATH", length = 510)
	public String getPhotoPath() {
		return this.photoPath;
	}

	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	@Column(name = "UNITS", length = 510)
	public String getUnits() {
		return this.units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

	@Column(name = "POSITION", length = 110)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "TITLE", length = 110)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "RESEARCH", length = 510)
	public String getResearch() {
		return this.research;
	}

	public void setResearch(String research) {
		this.research = research;
	}

	@Column(name = "SUMMERY")
	public Clob getSummery() {
		return this.summery;
	}

	public void setSummery(Clob summery) {
		this.summery = summery;
	}

	@Column(name = "REMARK", length = 510)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "LEVEL", length = 100)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ASSESSMENT_EXPERT", joinColumns = { @JoinColumn(name = "EXPERT_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ASSESSMENT_ID", nullable = false, updatable = false) })
	public Set<Assessment> getAssessments() {
		return this.assessments;
	}

	public void setAssessments(Set<Assessment> assessments) {
		this.assessments = assessments;
	}

}
