package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JointTaskDetail generated by hbm2java
 */
@Entity
@Table(name = "JOINT_TASK_DETAIL")
public class JointTaskDetail implements java.io.Serializable {

	private long id;
	private JointTask jointTask;
	private String inputer;
	private String processor;
	private String process;
	private String result;
	private String basis;
	private Character isLeader;
	private Character status;
	private Date completionTime;
	private Long dept;

	public JointTaskDetail() {
	}

	public JointTaskDetail(long id) {
		this.id = id;
	}

	public JointTaskDetail(long id, JointTask jointTask, String inputer,
			String processor, String process, String result, String basis,
			Character isLeader, Character status, Date completionTime, Long dept) {
		this.id = id;
		this.jointTask = jointTask;
		this.inputer = inputer;
		this.processor = processor;
		this.process = process;
		this.result = result;
		this.basis = basis;
		this.isLeader = isLeader;
		this.status = status;
		this.completionTime = completionTime;
		this.dept = dept;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOINT_TASK")
	public JointTask getJointTask() {
		return this.jointTask;
	}

	public void setJointTask(JointTask jointTask) {
		this.jointTask = jointTask;
	}

	@Column(name = "INPUTER", length = 110)
	public String getInputer() {
		return this.inputer;
	}

	public void setInputer(String inputer) {
		this.inputer = inputer;
	}

	@Column(name = "PROCESSOR", length = 110)
	public String getProcessor() {
		return this.processor;
	}

	public void setProcessor(String processor) {
		this.processor = processor;
	}

	@Column(name = "PROCESS", length = 1000)
	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	@Column(name = "RESULT", length = 510)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "BASIS", length = 510)
	public String getBasis() {
		return this.basis;
	}

	public void setBasis(String basis) {
		this.basis = basis;
	}

	@Column(name = "IS_LEADER", length = 1)
	public Character getIsLeader() {
		return this.isLeader;
	}

	public void setIsLeader(Character isLeader) {
		this.isLeader = isLeader;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COMPLETION_TIME", length = 11)
	public Date getCompletionTime() {
		return this.completionTime;
	}

	public void setCompletionTime(Date completionTime) {
		this.completionTime = completionTime;
	}

	@Column(name = "DEPT", precision = 10, scale = 0)
	public Long getDept() {
		return this.dept;
	}

	public void setDept(Long dept) {
		this.dept = dept;
	}

}
