package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JointTaskAttach generated by hbm2java
 */
@Entity
@Table(name = "JOINT_TASK_ATTACH")
public class JointTaskAttach implements java.io.Serializable {

	private long id;
	private JointTask jointTask;
	private String title;
	private String path;
	private String remark;

	public JointTaskAttach() {
	}

	public JointTaskAttach(long id) {
		this.id = id;
	}

	public JointTaskAttach(long id, JointTask jointTask, String title,
			String path, String remark) {
		this.id = id;
		this.jointTask = jointTask;
		this.title = title;
		this.path = path;
		this.remark = remark;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOINT_TASK")
	public JointTask getJointTask() {
		return this.jointTask;
	}

	public void setJointTask(JointTask jointTask) {
		this.jointTask = jointTask;
	}

	@Column(name = "TITLE", length = 510)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "PATH", length = 510)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "REMARK", length = 510)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
