package com.systop.fsmis.model;

// Generated 2009-12-16 9:41:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MedicalRescue generated by hbm2java
 */
@Entity
@Table(name = "MEDICAL_RESCUE")
public class MedicalRescue implements java.io.Serializable {

	private long id;
	private String deadQuantity;
	private Date handleDate;
	private String outQuantity;
	private String process;
	private String relateQuantity;
	private String rescueQuantity;
	private String result;

	public MedicalRescue() {
	}

	public MedicalRescue(long id) {
		this.id = id;
	}

	public MedicalRescue(long id, String deadQuantity, Date handleDate,
			String outQuantity, String process, String relateQuantity,
			String rescueQuantity, String result) {
		this.id = id;
		this.deadQuantity = deadQuantity;
		this.handleDate = handleDate;
		this.outQuantity = outQuantity;
		this.process = process;
		this.relateQuantity = relateQuantity;
		this.rescueQuantity = rescueQuantity;
		this.result = result;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "DEAD_QUANTITY", length = 510)
	public String getDeadQuantity() {
		return this.deadQuantity;
	}

	public void setDeadQuantity(String deadQuantity) {
		this.deadQuantity = deadQuantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HANDLE_DATE", length = 11)
	public Date getHandleDate() {
		return this.handleDate;
	}

	public void setHandleDate(Date handleDate) {
		this.handleDate = handleDate;
	}

	@Column(name = "OUT_QUANTITY", length = 510)
	public String getOutQuantity() {
		return this.outQuantity;
	}

	public void setOutQuantity(String outQuantity) {
		this.outQuantity = outQuantity;
	}

	@Column(name = "PROCESS", length = 510)
	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	@Column(name = "RELATE_QUANTITY", length = 510)
	public String getRelateQuantity() {
		return this.relateQuantity;
	}

	public void setRelateQuantity(String relateQuantity) {
		this.relateQuantity = relateQuantity;
	}

	@Column(name = "RESCUE_QUANTITY", length = 510)
	public String getRescueQuantity() {
		return this.rescueQuantity;
	}

	public void setRescueQuantity(String rescueQuantity) {
		this.rescueQuantity = rescueQuantity;
	}

	@Column(name = "RESULT", length = 510)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
