package com.systop.fsmis.model;

// Generated 2009-12-16 9:41:03 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Resources generated by hbm2java
 */
@Entity
@Table(name = "RESOURCES")
public class Resources implements java.io.Serializable {

	private long id;
	private Long version;
	private String descn;
	private String name;
	private String resString;
	private String resType;
	private Set<Permissions> permissionses = new HashSet<Permissions>(0);

	public Resources() {
	}

	public Resources(long id) {
		this.id = id;
	}

	public Resources(long id, String descn, String name, String resString,
			String resType, Set<Permissions> permissionses) {
		this.id = id;
		this.descn = descn;
		this.name = name;
		this.resString = resString;
		this.resType = resType;
		this.permissionses = permissionses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", precision = 10, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "DESCN", length = 510)
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	@Column(name = "NAME", length = 510)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "RES_STRING", length = 510)
	public String getResString() {
		return this.resString;
	}

	public void setResString(String resString) {
		this.resString = resString;
	}

	@Column(name = "RES_TYPE", length = 510)
	public String getResType() {
		return this.resType;
	}

	public void setResType(String resType) {
		this.resType = resType;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "PERMIS_RESC", joinColumns = { @JoinColumn(name = "RESC_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "PERMISSION_ID", nullable = false, updatable = false) })
	public Set<Permissions> getPermissionses() {
		return this.permissionses;
	}

	public void setPermissionses(Set<Permissions> permissionses) {
		this.permissionses = permissionses;
	}

}
