package com.systop.fsmis.model;

// Generated 2009-12-16 9:15:02 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "TASK")
public class Task implements java.io.Serializable {

	private long id;
	private GenericCase genericCase;
	private CompositiveCase compositiveCase;
	private String title;
	private String descn;
	private Date dispatchTime;
	private Date presetTime;
	private String status;
	private Set<TaskDetail> taskDetails = new HashSet<TaskDetail>(0);
	private Set<TaskAtt> taskAtts = new HashSet<TaskAtt>(0);

	public Task() {
	}

	public Task(long id) {
		this.id = id;
	}

	public Task(long id, GenericCase genericCase,
			CompositiveCase compositiveCase, String title, String descn,
			Date dispatchTime, Date presetTime, String status,
			Set<TaskDetail> taskDetails, Set<TaskAtt> taskAtts) {
		this.id = id;
		this.genericCase = genericCase;
		this.compositiveCase = compositiveCase;
		this.title = title;
		this.descn = descn;
		this.dispatchTime = dispatchTime;
		this.presetTime = presetTime;
		this.status = status;
		this.taskDetails = taskDetails;
		this.taskAtts = taskAtts;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GENERIC_CASE")
	public GenericCase getGenericCase() {
		return this.genericCase;
	}

	public void setGenericCase(GenericCase genericCase) {
		this.genericCase = genericCase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPOSITIVE_CASE")
	public CompositiveCase getCompositiveCase() {
		return this.compositiveCase;
	}

	public void setCompositiveCase(CompositiveCase compositiveCase) {
		this.compositiveCase = compositiveCase;
	}

	@Column(name = "TITLE", length = 510)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCN", length = 510)
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DISPATCH_TIME", length = 11)
	public Date getDispatchTime() {
		return this.dispatchTime;
	}

	public void setDispatchTime(Date dispatchTime) {
		this.dispatchTime = dispatchTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRESET_TIME", length = 11)
	public Date getPresetTime() {
		return this.presetTime;
	}

	public void setPresetTime(Date presetTime) {
		this.presetTime = presetTime;
	}

	@Column(name = "STATUS", length = 510)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<TaskDetail> getTaskDetails() {
		return this.taskDetails;
	}

	public void setTaskDetails(Set<TaskDetail> taskDetails) {
		this.taskDetails = taskDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<TaskAtt> getTaskAtts() {
		return this.taskAtts;
	}

	public void setTaskAtts(Set<TaskAtt> taskAtts) {
		this.taskAtts = taskAtts;
	}

}
