package com.systop.fsmis.model;

// Generated 2009-12-16 9:41:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskDetail generated by hbm2java
 */
@Entity
@Table(name = "TASK_DETAIL")
public class TaskDetail implements java.io.Serializable {

	private long id;
	private Task task;
	private Depts depts;
	private String inputer;
	private String processor;
	private String process;
	private String basis;
	private String result;
	private Date completionTime;
	private Character status;
	private String returnPeople;
	private String returnReason;

	public TaskDetail() {
	}

	public TaskDetail(long id) {
		this.id = id;
	}

	public TaskDetail(long id, Task task, Depts depts, String inputer,
			String processor, String process, String basis, String result,
			Date completionTime, Character status, String returnPeople,
			String returnReason) {
		this.id = id;
		this.task = task;
		this.depts = depts;
		this.inputer = inputer;
		this.processor = processor;
		this.process = process;
		this.basis = basis;
		this.result = result;
		this.completionTime = completionTime;
		this.status = status;
		this.returnPeople = returnPeople;
		this.returnReason = returnReason;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TASK")
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPT")
	public Depts getDepts() {
		return this.depts;
	}

	public void setDepts(Depts depts) {
		this.depts = depts;
	}

	@Column(name = "INPUTER", length = 110)
	public String getInputer() {
		return this.inputer;
	}

	public void setInputer(String inputer) {
		this.inputer = inputer;
	}

	@Column(name = "PROCESSOR", length = 110)
	public String getProcessor() {
		return this.processor;
	}

	public void setProcessor(String processor) {
		this.processor = processor;
	}

	@Column(name = "PROCESS", length = 1000)
	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	@Column(name = "BASIS", length = 510)
	public String getBasis() {
		return this.basis;
	}

	public void setBasis(String basis) {
		this.basis = basis;
	}

	@Column(name = "RESULT", length = 510)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COMPLETION_TIME", length = 11)
	public Date getCompletionTime() {
		return this.completionTime;
	}

	public void setCompletionTime(Date completionTime) {
		this.completionTime = completionTime;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "RETURN_PEOPLE", length = 110)
	public String getReturnPeople() {
		return this.returnPeople;
	}

	public void setReturnPeople(String returnPeople) {
		this.returnPeople = returnPeople;
	}

	@Column(name = "RETURN_REASON", length = 510)
	public String getReturnReason() {
		return this.returnReason;
	}

	public void setReturnReason(String returnReason) {
		this.returnReason = returnReason;
	}

}
