package com.systop.fsmis.model;

// Generated 2009-12-16 9:41:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UrgentCase generated by hbm2java
 */
@Entity
@Table(name = "URGENT_CASE")
public class UrgentCase implements java.io.Serializable {

	private long id;
	private String title;
	private Date caseTime;
	private String code;
	private String address;
	private String coordinate;
	private String cause;
	private String descn;
	private String involvedNum;
	private String deathNum;
	private String caseRange;
	private String plansLevel;
	private String hospital;
	private String reporter;
	private String reporterUnits;
	private String reporterPhone;
	private String status;
	private Date createTime;
	private String traffic;
	private Long auditor;
	private Date auditDate;
	private String auditOpinion;
	private Character isAgree;

	public UrgentCase() {
	}

	public UrgentCase(long id) {
		this.id = id;
	}

	public UrgentCase(long id, String title, Date caseTime, String code,
			String address, String coordinate, String cause, String descn,
			String involvedNum, String deathNum, String caseRange,
			String plansLevel, String hospital, String reporter,
			String reporterUnits, String reporterPhone, String status,
			Date createTime, String traffic, Long auditor, Date auditDate,
			String auditOpinion, Character isAgree) {
		this.id = id;
		this.title = title;
		this.caseTime = caseTime;
		this.code = code;
		this.address = address;
		this.coordinate = coordinate;
		this.cause = cause;
		this.descn = descn;
		this.involvedNum = involvedNum;
		this.deathNum = deathNum;
		this.caseRange = caseRange;
		this.plansLevel = plansLevel;
		this.hospital = hospital;
		this.reporter = reporter;
		this.reporterUnits = reporterUnits;
		this.reporterPhone = reporterPhone;
		this.status = status;
		this.createTime = createTime;
		this.traffic = traffic;
		this.auditor = auditor;
		this.auditDate = auditDate;
		this.auditOpinion = auditOpinion;
		this.isAgree = isAgree;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "TITLE", length = 510)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CASE_TIME", length = 11)
	public Date getCaseTime() {
		return this.caseTime;
	}

	public void setCaseTime(Date caseTime) {
		this.caseTime = caseTime;
	}

	@Column(name = "CODE", length = 110)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "ADDRESS", length = 510)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "COORDINATE", length = 510)
	public String getCoordinate() {
		return this.coordinate;
	}

	public void setCoordinate(String coordinate) {
		this.coordinate = coordinate;
	}

	@Column(name = "CAUSE", length = 510)
	public String getCause() {
		return this.cause;
	}

	public void setCause(String cause) {
		this.cause = cause;
	}

	@Column(name = "DESCN", length = 4000)
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	@Column(name = "INVOLVED_NUM", length = 110)
	public String getInvolvedNum() {
		return this.involvedNum;
	}

	public void setInvolvedNum(String involvedNum) {
		this.involvedNum = involvedNum;
	}

	@Column(name = "DEATH_NUM", length = 110)
	public String getDeathNum() {
		return this.deathNum;
	}

	public void setDeathNum(String deathNum) {
		this.deathNum = deathNum;
	}

	@Column(name = "CASE_RANGE", length = 510)
	public String getCaseRange() {
		return this.caseRange;
	}

	public void setCaseRange(String caseRange) {
		this.caseRange = caseRange;
	}

	@Column(name = "PLANS_LEVEL", length = 110)
	public String getPlansLevel() {
		return this.plansLevel;
	}

	public void setPlansLevel(String plansLevel) {
		this.plansLevel = plansLevel;
	}

	@Column(name = "HOSPITAL", length = 510)
	public String getHospital() {
		return this.hospital;
	}

	public void setHospital(String hospital) {
		this.hospital = hospital;
	}

	@Column(name = "REPORTER", length = 510)
	public String getReporter() {
		return this.reporter;
	}

	public void setReporter(String reporter) {
		this.reporter = reporter;
	}

	@Column(name = "REPORTER_UNITS", length = 510)
	public String getReporterUnits() {
		return this.reporterUnits;
	}

	public void setReporterUnits(String reporterUnits) {
		this.reporterUnits = reporterUnits;
	}

	@Column(name = "REPORTER_PHONE", length = 110)
	public String getReporterPhone() {
		return this.reporterPhone;
	}

	public void setReporterPhone(String reporterPhone) {
		this.reporterPhone = reporterPhone;
	}

	@Column(name = "STATUS", length = 110)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 11)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "TRAFFIC", length = 510)
	public String getTraffic() {
		return this.traffic;
	}

	public void setTraffic(String traffic) {
		this.traffic = traffic;
	}

	@Column(name = "AUDITOR", precision = 10, scale = 0)
	public Long getAuditor() {
		return this.auditor;
	}

	public void setAuditor(Long auditor) {
		this.auditor = auditor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUDIT_DATE", length = 11)
	public Date getAuditDate() {
		return this.auditDate;
	}

	public void setAuditDate(Date auditDate) {
		this.auditDate = auditDate;
	}

	@Column(name = "AUDIT_OPINION", length = 510)
	public String getAuditOpinion() {
		return this.auditOpinion;
	}

	public void setAuditOpinion(String auditOpinion) {
		this.auditOpinion = auditOpinion;
	}

	@Column(name = "IS_AGREE", length = 1)
	public Character getIsAgree() {
		return this.isAgree;
	}

	public void setIsAgree(Character isAgree) {
		this.isAgree = isAgree;
	}

}
