INSERT INTO URGENT_GROUPS(ID, NAME, CATEGORY, IS_ORIGINAL, IS_PUBLIC, COUNTY) VALUES ($ID, '指挥部', 'Leadership', 1, 1, $COUNTY);
INSERT INTO URGENT_GROUPS(ID, NAME, CATEGORY, IS_ORIGINAL, IS_PUBLIC, COUNTY) VALUES ($ID, '办公室', 'Office', 1, 1, $COUNTY);
INSERT INTO URGENT_GROUPS(ID, NAME, CATEGORY, IS_ORIGINAL, IS_PUBLIC, COUNTY) VALUES ($ID, '警戒保卫组', 'Defend', 1, 1, $COUNTY);
INSERT INTO URGENT_GROUPS(ID, NAME, CATEGORY, IS_ORIGINAL, IS_PUBLIC, COUNTY) VALUES ($ID, '医疗救护组', 'MedicalRescue', 1, 1, $COUNTY);
INSERT INTO URGENT_GROUPS(ID, NAME, CATEGORY, IS_ORIGINAL, IS_PUBLIC, COUNTY) VALUES ($ID, '后勤保障组', 'RearService', 1, 1, $COUNTY);
INSERT INTO URGENT_GROUPS(ID, NAME, CATEGORY, IS_ORIGINAL, IS_PUBLIC, COUNTY) VALUES ($ID, '新闻报道组', 'NewsReport', 1, 1, $COUNTY);
INSERT INTO URGENT_GROUPS(ID, NAME, CATEGORY, IS_ORIGINAL, IS_PUBLIC, COUNTY) VALUES ($ID, '专家技术组', 'NewsReport', 1, 1, $COUNTY);
INSERT INTO URGENT_GROUPS(ID, NAME, CATEGORY, IS_ORIGINAL, IS_PUBLIC, COUNTY) VALUES ($ID, '接待', 'Receive', 1, 1, $COUNTY);
