INSERT INTO SEND_TYPES(ID, NAME, DESCN, SORT_ID) VALUES (1, '初级农产品环节', '初级农产品', 1);
INSERT INTO SEND_TYPES(ID, NAME, DESCN, SORT_ID) VALUES (2, '食品生产加工环节', '食品生产加工环节', 2);
INSERT INTO SEND_TYPES(ID, NAME, DESCN, SORT_ID) VALUES (3, '食品流通环节', '食品流通环节', 3);
INSERT INTO SEND_TYPES(ID, NAME, DESCN, SORT_ID) VALUES (4, '餐饮消费环节', '餐饮消费环节', 4);
INSERT INTO SEND_TYPES(ID, NAME, DESCN, SORT_ID) VALUES (5, '其他环节', '其他环节', 5);